import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/navbar";
import Sidebar from "./components/Sidebar";
import { Providers } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="scrollbar-thumb-gray-900 scrollbar-track-gray-800">
          <Navbar />
          <div className="container h-[calc(100vh-98px)] flex gap-5 overflow-hidden">
            <Sidebar />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
