import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavReuseble from "@/components/reuseble/nav-reuseble";
import SidebarComponent from "@/components/sidebars-component";
import QueryProvider from "@/components/providers/query-provider";
import { getServerSession } from "next-auth";
import SessionAuthProvider from "@/components/providers/session-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Honey Movie",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionAuthProvider session={session}>
          <QueryProvider>
            <main className="flex flex-col min-h-screen">
              <NavReuseble />
              <main className="container md:h-[calc(100vh-100px)] flex gap-5 overflow-hidden">
                <SidebarComponent />
                {children}
              </main>
            </main>
          </QueryProvider>
        </SessionAuthProvider>
      </body>
    </html>
  );
}
